UnityForm.Web/Models/Address.cs
namespace UnityForm.Web.Models
{
    public class Address : Entity
    {
        public string Street { get; set; }
        public string StreetNo { get; set; }
        public string PostCode { get; set; }

        public int CityId { get; set; }
        public virtual City City { get; set; }
    }
}

UnityForm.Web/Models/AddressViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace UnityForm.Web.Models
{
    public class AddressViewModel
    {
        public IEnumerable<City> Cities { get; set; }

        [Display(Name = "Ulica")]
        public string Street { get; set; }

        [Display(Name = "Numer")]
        public string StreetNo { get; set; }

        [Display(Name = "Kod Pocztowy")]
        public string PostCode { get; set; }

        [Display(Name = "Miasto")]
        public int? CityId { get; set; }
    }
}

UnityForm.Web/Models/City.cs
namespace UnityForm.Web.Models
{
    public class City : Entity
    {
        public string Name { get; set; }
        public string County { get; set; }
        public string Province { get; set; }
    }
}

UnityForm.Web/Models/Customer.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace UnityForm.Web.Models
{
    public class Customer : Entity
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }

        public int AddressId { get; set; }

        [ForeignKey("AddressId")]
        public virtual Address Address { get; set; }

        public int CorrespondenceAddressId { get; set; }

        [ForeignKey("CorrespondenceAddressId")]
        public virtual Address CorrespondenceAddress { get; set; }
    }
}

UnityForm.Web/Models/CustomerViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace UnityForm.Web.Models
{
    public class CustomerViewModel
    {
        [Required]
        [Display(Name = "Imię")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Data urodzenia")]
        [DataType(DataType.Date, ErrorMessage = "Podana wartość jest nieprawidłowa dla daty urodzenia.")]
        public DateTime? DateOfBirth { get; set; }
    }
}

UnityForm.Web/Models/Entity.cs
namespace UnityForm.Web.Models
{
    public class Entity
    {
        public int Id { get; set; }
    }
}

UnityForm.Web/Models/FormViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace UnityForm.Web.Models
{
    public class FormViewModel : IValidatableObject
    {
        public FormViewModel()
        {
            Address = new AddressViewModel();
            CorrespondenceAddress = new AddressViewModel();
        }

        public CustomerViewModel Customer { get; set; }

        public AddressViewModel Address { get; set; }

        [Display(Name = "Adres korespondencyjny taki jak adres zameldowania")]
        public bool IsCorrespondenceAddressSame { get; set; }

        public AddressViewModel CorrespondenceAddress { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (string.IsNullOrWhiteSpace(Address.Street))
                yield return new ValidationResult("Pole Ulica jest wymagane.", new[] {"Address.Street"});
            if (string.IsNullOrWhiteSpace(Address.StreetNo))
                yield return new ValidationResult("Pole Numer jest wymagane.", new[] {"Address.StreetNo"});
            if (Address.CityId == null)
                yield return new ValidationResult("Pole Miasto jest wymagane.", new[] {"Address.CityId"});
            if (string.IsNullOrWhiteSpace(Address.PostCode))
                yield return new ValidationResult("Pole Kod pocztowy jest wymagane.", new[] {"Address.PostCode"});

            if (!IsCorrespondenceAddressSame)
            {
                if (string.IsNullOrWhiteSpace(CorrespondenceAddress.Street))
                    yield return
                        new ValidationResult("Pole Ulica jest wymagane.", new[] {"CorrespondenceAddress.Street"});
                if (string.IsNullOrWhiteSpace(CorrespondenceAddress.StreetNo))
                    yield return
                        new ValidationResult("Pole Numer jest wymagane.", new[] {"CorrespondenceAddress.StreetNo"});
                if (CorrespondenceAddress.CityId == null)
                    yield return
                        new ValidationResult("Pole Miasto jest wymagane.", new[] {"CorrespondenceAddress.CityId"});
                if (string.IsNullOrWhiteSpace(CorrespondenceAddress.PostCode))
                    yield return
                        new ValidationResult("Pole Kod pocztowy jest wymagane.",
                            new[] {"CorrespondenceAddress.PostCode"});
            }
        }
    }
}

UnityForm.Web/Controllers/BaseController.cs
using System.Web.Mvc;
using FormContext = UnityForm.Web.DataAccess.FormContext;

namespace UnityForm.Web.Controllers
{
    public class BaseController : Controller
    {
        protected FormContext Context;

        public BaseController()
        {
            Context = new FormContext();
            Context.Database.CreateIfNotExists();
        }
    }
}

UnityForm.Web/Controllers/ErrorController.cs
using System.Net;
using System.Web.Mvc;

namespace UnityForm.Web.Controllers
{
    public class ErrorController : Controller
    {
        public ViewResult NotFound()
        {
            Response.TrySkipIisCustomErrors = true;
            Response.StatusCode = (int)HttpStatusCode.NotFound;
            return View("NotFound");
        }

        public ViewResult Unknown()
        {
            Response.StatusCode = (int)HttpStatusCode.OK;
            Response.TrySkipIisCustomErrors = true;
            return View("Unknown");
        }
    }
}

UnityForm.Web/Controllers/FormController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UnityForm.Web.Contracts;
using UnityForm.Web.Models;
using UnityForm.Web.Services;

namespace UnityForm.Web.Controllers
{
    public class FormController : BaseController
    {
        private readonly ICustomerService _service;

        public FormController()
        {
            _service = new CustomerService(Context);
        }

        private List<City> GetCities()
        {
            if (TempData.ContainsKey("Cities"))
                return (List<City>) TempData.Peek("Cities");

            var cities = Context.City.ToList();
            TempData.Add("Cities", cities);

            return cities;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new FormViewModel();

            var cities = GetCities();
            model.Address.Cities = cities;
            model.CorrespondenceAddress.Cities = cities;

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(FormViewModel model)
        {
            if (ModelState.IsValid)
            {
                var addressId = _service.AddCustomerAddress(model.Address);
                var correspondaceAddressId = model.IsCorrespondenceAddressSame
                    ? addressId
                    : _service.AddCustomerAddress(model.CorrespondenceAddress);

                _service.AddCustomer(model.Customer, addressId, correspondaceAddressId);

                return RedirectToAction("Index", "Home", new {messageId = 1});
            }

            var cities = GetCities();
            model.Address.Cities = cities;
            model.CorrespondenceAddress.Cities = cities;
            return View("Index", model);
        }
    }
}

UnityForm.Web/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UnityForm.Web.Models;

namespace UnityForm.Web.Controllers
{
    public class HomeController : BaseController
    {
        [HttpGet]
        public ActionResult Index(int messageId = 0)
        {
            if (messageId == 1)
                ViewBag.Message = "Formularz został poprawnie zapisany.";

            var data = Context.Customer.Any() ? Context.Customer.ToList() : new List<Customer>();

            return View(data);
        }
    }
}

UnityForm.Web/Views/Form/Index.cshtml
@model FormViewModel
@{
    ViewBag.Title = "Formularz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Add", "Form", FormMethod.Post))
{
    <h2>Wypełnij poniższy formularz:</h2>
    
    @Html.EditorFor(m => m.Customer, "_Customer")

    <div>
        <p>Adres zameldowania:</p>
        @Html.EditorFor(m => m.Address, "_Address")
    </div>

    <div class="row">
        <div class="form-group col-sm-3">
            @Html.LabelFor(m => m.IsCorrespondenceAddressSame, new {@class = "control-label"})
        </div>
        <div class="col-sm-3">
            @Html.CheckBoxFor(m => m.IsCorrespondenceAddressSame)
        </div>
    </div>

    <div id="correspondence">
        <p>Adres korespondencyjny:</p>
        @Html.EditorFor(m => m.CorrespondenceAddress, "_Address")
    </div>

    <div>
        <input class="btn btn-primary" type="submit" value="Prześlij"/>
        @Html.ActionLink("Anuluj","Index", "Home", null, new { @class = "btn btn-default" })
    </div>
}

@section Scripts {
    <script type="text/javascript">
        function ShowHideCorrespondencePart($el) {
            if ($el.is(':checked')) {
                $("#correspondence").hide();
            } else {
                $("#correspondence").show();
            }
        }

        ShowHideCorrespondencePart($('#IsCorrespondenceAddressSame'));

        $(function() {
            $("#IsCorrespondenceAddressSame").click(function() {
                ShowHideCorrespondencePart($(this));
            });
        });
    </script>
}

UnityForm.Web/Views/Home/Index.cshtml
@model IEnumerable<Customer>
@{
    ViewBag.Title = "Strona Domowa";
}

<p class="has-success">@ViewBag.Message</p>
<div>
    @Html.ActionLink("Dodaj Formularz", "Index", "Form", null, new {@class= "btn btn-primary" })
</div>

<div>
    <h2>Lista przesłanych formualarzy:</h2>
    @{
        if (Model.Any())
        {
            <div class="row uppercase">
                <div class="col-sm-2">Imię</div>
                <div class="col-sm-2">Nazwisko</div>
                <div class="col-sm-2">Data Urodzenia</div>
                <div class="col-sm-2">Miasto</div>
                <div class="col-sm-2">Powiat</div>
                <div class="col-sm-2">Województwo</div>
            </div>
            <hr/>
            foreach (var customer in Model)
            {
                <div class="row">
                    <div class="col-sm-2">
                        @customer.FirstName
                    </div>
                    <div class="col-sm-2">
                        @customer.LastName
                    </div>
                    <div class="col-sm-2">
                        @customer.DateOfBirth
                    </div>
                    <div class="col-sm-2">
                        @customer.Address.City.Name
                    </div>
                    <div class="col-sm-2">
                        @customer.Address.City.County
                    </div>
                    <div class="col-sm-2">
                        @customer.Address.City.Province
                    </div>
                    </div>
            }
        }
        else
        {
            <div>Nie dodano jeszcze żadnych danych.</div>
        }
    }
</div>

UnityForm.Web/Views/Shared/EditorTemplates/_Address.cshtml
@model AddressViewModel
    
@Html.EditorFor(m => m.Street, "_TextBox")
@Html.EditorFor(m => m.StreetNo, "_TextBox")
@Html.EditorFor(m => m.PostCode, "_TextBox")

<div class="form-group">
    <div class="row">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.CityId, new {@class = "control-label"})
        </div>
        <div class="col-sm-5">
            @Html.DropDownListFor(m => m.CityId, Model.Cities.Select(p => new SelectListItem
            {
                Selected = p.Id == Model.CityId,
                Text = p.Name,
                Value = p.Id.ToString()
            }), new {@class = "form-control"})
        </div>
    </div>
    <div class="has-error">
        @Html.ValidationMessageFor(m => m.CityId)
    </div>
</div>

UnityForm.Web/Views/Shared/EditorTemplates/_Customer.cshtml
@model CustomerViewModel

@Html.EditorFor(m => m.FirstName, "_TextBox")
@Html.EditorFor(m => m.LastName, "_TextBox")

<div class="form-group">
    <div class="row">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.DateOfBirth, new { @class = "control-label" })
        </div>
        <div class="col-sm-5">
            @Html.TextBoxFor(m => m.DateOfBirth, new { @class = "form-control", placeholder= "DD-MM-RRRR" })
        </div>
    </div>
    <div class="has-error">
        @Html.ValidationMessageFor(m => m.DateOfBirth)
    </div>
</div>

UnityForm.Web/Views/Shared/EditorTemplates/_TextBox.cshtml
@model string

<div class="form-group">
    <div class="row">
        <div class="col-sm-3">
            @Html.LabelFor(m => m, new {@class = "control-label"})
        </div>
        <div class="col-sm-5">
            @Html.TextBoxFor(m => m, new {@class = "form-control"})
        </div>
    </div>
    <div class="has-error">
        @Html.ValidationMessageFor(m => m)
    </div>
</div>

UnityForm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Unity</title>
    @Styles.Render("~/Content/css")
</head>
<body>
<section class="container">
    <header class="row">
        <div class="col-sm-12 page-header">
            <h1>Unity Formularz - <small>@ViewBag.Title</small></h1>
        </div>
    </header>
    @RenderBody()
    <footer class="row" style="margin-top: 50px;">
        <div class="col-sm-12 panel-footer">
            <p>&copy; @DateTime.Now.Year - Unity</p>
        </div>
    </footer>
</section>

@Scripts.Render("~/bundles/js")
@RenderSection("scripts", required: false)
</body>
</html>